from dataclasses import dataclass
from hashlib import sha256

from app.schemas.hosts import HostCreate
from app.schemas.subnets import SubnetCreate


class DhcpConfigurationError(ValueError):
    pass


@dataclass(frozen=True)
class GeneratedConfiguration:
    content: str
    sha256: str


ALLOWED_ADDITIONAL_OPTIONS = frozenset({"domain-search", "ntp-servers"})


def _reject_unsafe_options(options: dict[str, str]) -> None:
    for name, value in options.items():
        candidate = f"{name} {value}".lower()
        if name == "range" or "range " in candidate:
            raise DhcpConfigurationError("DHCP directive 'range' is forbidden")
        if name not in ALLOWED_ADDITIONAL_OPTIONS:
            raise DhcpConfigurationError(f"DHCP option '{name}' is not on the controlled allowlist")
        if any(character in candidate for character in ("\n", "\r", ";", "{", "}")):
            raise DhcpConfigurationError("DHCP options must come from a controlled allowlist")


def _render_option(name: str, value: str) -> str:
    return f"    option {name} {value};"


def generate_dhcpd_conf(
    subnets: list[SubnetCreate], hosts: list[HostCreate]
) -> GeneratedConfiguration:
    """Create a full deterministic static-only configuration; raw snippets are never accepted."""
    for subnet in subnets:
        _reject_unsafe_options(subnet.additional_options)
    for host in hosts:
        _reject_unsafe_options(host.additional_options)

    active_subnets = sorted(
        (subnet for subnet in subnets if subnet.is_active), key=lambda item: str(item.network)
    )
    active_hosts = sorted(
        (host for host in hosts if host.is_active),
        key=lambda item: (item.subnet_name, item.ipv4_address),
    )
    lines = [
        "# Generated by DHCP Manager. Do not edit manually.",
        "authoritative;",
        "deny unknown-clients;",
        "default-lease-time 86400;",
        "max-lease-time 86400;",
        "",
    ]

    subnets_by_name = {subnet.name: subnet for subnet in active_subnets}
    for subnet in active_subnets:
        if subnet.gateway and subnet.gateway not in subnet.network:
            raise DhcpConfigurationError(f"Gateway is outside subnet {subnet.name}")
        lines.append(f"subnet {subnet.network.network_address} netmask {subnet.network.netmask} {{")
        lines.append(f"    option subnet-mask {subnet.network.netmask};")
        if subnet.gateway:
            lines.append(f"    option routers {subnet.gateway};")
        if subnet.dns_servers:
            lines.append(
                "    option domain-name-servers " + ", ".join(map(str, subnet.dns_servers)) + ";"
            )
        if subnet.dns_domain:
            lines.append(f'    option domain-name "{subnet.dns_domain}";')
        for name, value in sorted(subnet.additional_options.items()):
            lines.append(_render_option(name, value))

        for host in (item for item in active_hosts if item.subnet_name == subnet.name):
            if host.ipv4_address not in subnet.network:
                raise DhcpConfigurationError(
                    f"Host {host.hostname} is outside subnet {subnet.name}"
                )
            if host.ipv4_address in {
                subnet.network.network_address,
                subnet.network.broadcast_address,
            }:
                raise DhcpConfigurationError(
                    f"Host {host.hostname} uses a network or broadcast address"
                )
            if subnet.gateway and host.ipv4_address == subnet.gateway:
                raise DhcpConfigurationError(f"Host {host.hostname} uses the gateway address")
            lines.extend(
                [
                    f"    host {host.hostname} {{",
                    f"        hardware ethernet {host.mac_address};",
                    f"        fixed-address {host.ipv4_address};",
                    "    }",
                ]
            )
        lines.extend(["}", ""])

    unassigned = {host.subnet_name for host in active_hosts}.difference(subnets_by_name)
    if unassigned:
        raise DhcpConfigurationError(
            f"Hosts refer to unknown subnets: {', '.join(sorted(unassigned))}"
        )
    content = "\n".join(lines).rstrip() + "\n"
    if "range" in content.lower():
        raise DhcpConfigurationError("DHCP directive 'range' is forbidden")
    return GeneratedConfiguration(content=content, sha256=sha256(content.encode()).hexdigest())
